### ISSUE TITLE
APU chip select

### ISSUE THREAD

**Issue by b1ackmai1er** [crsjones/Southern-Cross-Computer-z80#7]
Hi, On your APU R3 board, I think you should have nIORQ going to pin 3 of the LS688 not nMREQ. Regards Phil.

**Comment by crsjones** [comment]
Hi Phil, No, the timing of chip select to the AM9511A is different to the Read Write timing. 
If you look at the HC688 you will see that the output will only go low when there is a address match and /MREQ is High (P0 = Q0). 
The /IOREQ  gates the /RD and /WR which controls the data transfer, /CS is already low before /IOREQ  as during this I/O cycle /MREQ is High. 
You should look at Philip Stevens original circuit and description to satisfy yourself that this is correct.  
Regards
Craig

**Comment by b1ackmai1er** [comment]
Hi Craig, Thank you for your quick reply. 
Thank you, I would never have figured this out, thinking that the /CS was standard 688 configuration. I was finding I could read from the chip but could not write to it. Back to the drawing board, track cutter, hookup wire and soldering iron. Cheers!
